name: .NET Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_GITHUB_USERNAME: ${{ github.repository_owner }}
      NUGET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore ./EcAuth.sln

    - name: Build
      working-directory: ./MockOpenIdProvider.Test
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./MockOpenIdProvider.Test
      run: dotnet test --no-build --verbosity normal

    - name: Build
      working-directory: ./IdentityProvider.Test
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./IdentityProvider.Test
      run: dotnet test --no-build --verbosity normal
